### ISSUE TITLE
Version in Joplin repo is still at 1.0.0

### ISSUE THREAD

**Issue by KhaaL** [FelisDiligens/joplin-plugin-multimd-table-tools#3]
Hello and thank you for this excellent plugin.

I just want to raise awareness that the version in the Joplin repos is still at 1.0.0. A minor version behind, but a reminder nonetheless to keep it up to date.

**Comment by FelisDiligens** [comment]
Hi, I updated the plugin and the repo has picked it up now.
Last time, it somehow failed.
Let me now, if there are any more issues. :)
