### ISSUE TITLE
Joplin crashes when I add non-dash characters on the table divider

### ISSUE THREAD

**Issue by uyrussell21** [FelisDiligens/joplin-plugin-multimd-table-tools#5]
When I add a non-dash character on the table divider, the app hangs and becomes unusable until restarted

e.g.

```md
| Header 1 | Header 2 |
|----------|-----5-----|
|    hello |    world |
```

**Comment by FelisDiligens** [comment]
Hi @uyrussell21,
thanks for the report! It should be fixed in the update [v1.2.0](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/releases/tag/1.2.0).
I will close the issue now. Feel free to tell me, if there are any more issues.
