### ISSUE TITLE
Error: "No table found at cursor position" when trying to search

### ISSUE THREAD

**Issue by jramnani** [FelisDiligens/joplin-plugin-multimd-table-tools#6]
Joplin's default keyboard shortcut for `Cmd+Shift+f` on macOS is "Search in all the notes".

![image](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/assets/68455/1a1f1136-4884-4482-afab-542514f651a5)

When I install and enable the MultiMarkdown Table Tools plugin, and I try to search my notes via the keyboard shortcut, `Cmd+Shift+f`, then I get the following error dialogue, instead of taking my cursor into the Find box.

![image](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/assets/68455/a1524668-35f4-4188-a50d-eccf04ccef21)

Here are the other plugins I have installed. For me, this error goes away when I disable the MultiMarkdown Table Tools plugin.

![image](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/assets/68455/dad5789f-1137-4c4e-b47a-ec296010ffd4)

I wonder if I can disable that keyboard shortcut, or if that action can be remapped to another keyboard shortcut that doesn't trigger a conflict?  Although I am not sure what might be triggering that exact error message. 🤔 

Thanks for writing this plugin, and I hope this report is useful.

**Comment by FelisDiligens** [comment]
Hi, sorry for responding late and thanks for reporting.

Have you tried disabling hotkeys in the plugin's settings (Tools → Options → MultiMarkdown Table Tools)?
![Screenshot_20240316_163019](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/assets/47528453/264f1fc0-beb3-4b2e-8269-ce669afad5c3)

(Although this will disable all hotkeys such as Tab, Shift+Tab, Enter, and so on...)

The error message appears if the plugin doesn't find a table at/near the cursor in the editor. Ctrl+Shift+F is currently bound to "Format table".

**EDIT:** I just released update [v1.2.0](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/releases/tag/1.2.0), which adds a new option:
![Screenshot_20240316_192359](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/assets/47528453/e6b2db75-0b55-4ee7-a9e0-05b307d8afb4)

This disables the Cmd+Shift+F hotkey in the plugin, so you can use it for search.

**Comment by jramnani** [comment]
I ended up remapping the "Format Table" command and moved it to something that made sense for me in my setup.

![image](https://github.com/FelisDiligens/joplin-plugin-multimd-table-tools/assets/68455/ba49a181-a53f-4cc0-a440-efcf6f1a07f9)

Now I can hit Tab and my Markdown table formats nicely, and I can use `Cmd+f` and `Cmd+Shift+f` for searching.  🎉 

This made me appreciate Joplin's ability to customize the keymap. It allows for both customization and a way for me to workaround conflicts between keyboard shortcuts like this.

Thanks for the reply. And again, thanks for writing this plugin.  :)
