### ISSUE TITLE
Would it be possible to keep cell span after "format table"?

### ISSUE THREAD

**Issue by blueball81** [FelisDiligens/joplin-plugin-multimd-table-tools#9]
Hi, I like your plugin to handle markdown table in Joplin.

This is my original table with span cells with it.
![image](https://github.com/user-attachments/assets/2f80d58c-05d0-4243-9f6f-c763cccb4cd5)

Once I apply "Format Table", the table looks nice, but I found horizontal span cells are no more spanned as in the following.
![image](https://github.com/user-attachments/assets/258cc561-8916-4220-9799-0c8420499d18)

I know that span cell needs two or more repeating '|' .  Thus, it would be something like this will look fine. 
![image](https://github.com/user-attachments/assets/86ef50ff-8bb6-43b3-8a59-7ae38de7cc7d)

It would be great, if this plugin works in this way to support spanned cells. 
Thanks,

**Comment by FelisDiligens** [comment]
Hi @blueball81,
this surprises me as I cannot reproduce this issue...

https://github.com/user-attachments/assets/67bf22c2-7f67-423d-b03e-039a8f3b1d23

Did you select "MultiMarkdown" as the "Table format" in the settings?

![grafik](https://github.com/user-attachments/assets/7eb773ac-efde-4470-9bfd-68fd84e8728c)

![grafik](https://github.com/user-attachments/assets/edcfe854-a775-4c8e-97e9-7720f00608a8)

Is there maybe a conflict with another extension?

**Comment by blueball81** [comment]
Got it. Mine was 'Github Flavored Markdown'.
I changed the table format to MultiMarkdown, and now span cells are kept after table formatting.  Thanks!
